add missing gcc debian dependancy
I believe that you are missing the gcc dependency on debian system.
At least on my Jessie (docker based) system I need it to avoid error like :

  unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1